package de.travelmate.planning;

public enum SpatialCoverageWarningCode {
    IMPORT_RADIUS_TOO_SMALL_FOR_LONG_TRIP,
    CENTER_BIAS_DOMINATES_IMPORT,
    INTEREST_ONLY_HAS_CENTER_CANDIDATES,
    IMPORT_SPATIAL_COVERAGE_INSUFFICIENT,
    MULTI_AREA_IMPORT_RECOMMENDED,
    MULTI_AREA_IMPORT_TRIGGERED
}
