package de.travelmate.planning;

public enum SpatialWarningCode {
    SPATIAL_DIVERSITY_LOW,
    DOMINANT_CENTER_CLUSTER,
    TOO_MANY_ACTIVITIES_IN_ONE_CLUSTER,
    REPEATED_CLUSTER_ACROSS_DAYS,
    LOW_DISTANCE_FROM_CITY_CENTER,
    INSUFFICIENT_COORDINATES_FOR_SPATIAL_DIAGNOSTICS,
    MULTI_AREA_IMPORT_RECOMMENDED
}
