ALTER TABLE trips
  ADD COLUMN country VARCHAR(255),
  ADD COLUMN country_code VARCHAR(16),
  ADD COLUMN state VARCHAR(255),
  ADD COLUMN latitude DOUBLE PRECISION,
  ADD COLUMN longitude DOUBLE PRECISION,
  ADD COLUMN place_id VARCHAR(255);
